name: Build
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup MSBuild.exe
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.os }}-deps

      - name: Dependencies
        run: yarn

      - name: Build
        run: yarn package

      - name: Prepare to Deploy
        id: before_deploy
        shell: bash
        run: |
          rm -rf ./release/*.blockmap
          rm -rf ./release/*.zip
          rm -rf ./release/*-unpacked
          rm -rf ./release/mac
          export NAME=$(ls release/CirqWallet*)
          echo ::set-output name=file_name::${NAME:8}

      - name: Store Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: build_dir
          path: ./release

      - name: Upload to GH Release
        if: github.event_name == 'release' && github.repository == 'cirquity/cirquity-wallet'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/${{ steps.before_deploy.outputs.file_name }}
          asset_name: ${{ steps.before_deploy.outputs.file_name }}
          asset_content_type: application/octet-stream
